CREATE TYPE privileges AS ENUM ('ADMIN', 'GOD', 'LILGOD', 'MAPPER', 'USHER');

CREATE TABLE "COMPANIES" ("ID" serial NOT NULL,"NAME" varchar(50) NOT NULL UNIQUE,"LOGO" text NOT NULL,CONSTRAINT companies_pk PRIMARY KEY ("ID"));



CREATE TABLE "OFFICES" ("ID" serial NOT NULL,"NAME" varchar(50),"DIR" varchar(50),"COMPANIES_FK" serial NOT NULL,CONSTRAINT offices_pk PRIMARY KEY ("ID"));



CREATE TABLE "FLOORS" ("FLOOR" integer NOT NULL,"BASEMAP" text NOT NULL,"PLACESMAP" text NOT NULL,"EMERGENCYMAP" text NOT NULL,"OFFICES_FK" serial NOT NULL);



CREATE TABLE "USERS" ("ID" integer NOT NULL,"NAME" varchar(50) NOT NULL,"SURNAME" varchar(50) NOT NULL,"MAIL" varchar(50) NOT NULL UNIQUE,"PASS" varchar NOT NULL,"SALT" varchar NOT NULL,"PRIVILEGES" privileges NOT NULL,"OFFICE_FK" integer NOT NULL);


ALTER TABLE "OFFICES" ADD CONSTRAINT "office_fk0" FOREIGN KEY ("COMPANIES_FK") REFERENCES "COMPANIES"("ID");

ALTER TABLE "FLOORS" ADD CONSTRAINT "floor_fk0" FOREIGN KEY ("OFFICES_FK") REFERENCES "OFFICES"("ID");

ALTER TABLE "USERS" ADD CONSTRAINT "user_fk0" FOREIGN KEY ("OFFICES_FK") REFERENCES "OFFICES"("ID");

